tests: Replace errors.Is(err, nil) usage with testify and automate check

diff --git a/.github/workflows/misc.yml b/.github/workflows/misc.yml
--- a/.github/workflows/misc.yml
+++ b/.github/workflows/misc.yml
@@ -38,3 +38,9 @@ jobs:
           echo "::error::Replace \"should\" in require messages and \"must\" in assert messages"
           exit 1
         fi
+    
+    - name: Check for errors.Is(err, nil) usage
+      run: |
+        grep -r -n --include='*_test.go' --color=always -E "errors.Is\([^,]+, nil" . || exit 0
+        echo "::error::Replace errors.Is(err, nil) with testify equivalents"
+        exit 1
